# Generated by Django 3.0.8 on 2020-07-15 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('ISBN', models.CharField(max_length=25)),
                ('copies', models.IntegerField()),
                ('publisher', models.CharField(max_length=25)),
                ('copies_available', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('other_name', models.CharField(max_length=25)),
                ('photo', models.ImageField(upload_to='uploads')),
                ('phone', models.CharField(max_length=25)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_user', to='core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now=True)),
                ('date_returned', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned')], default='Borrowed', max_length=25)),
                ('extra_details', models.TextField()),
                ('borrow_date', models.DateField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed', to='core.LibraryUser')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='core.Book')),
                ('issuing_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuing_staff', to=settings.AUTH_USER_MODEL)),
                ('recieving_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieving_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.BookCategory'),
        ),
    ]
