# Generated by Django 3.0.8 on 2020-07-15 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200715_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='recieving_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieving_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
